{"name": "Verify Login with Invalid Credentials -- @1.2 credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\steps\\loginpagesteps\\loginpagesteps.py\", line 68, in userErrorMessage\n    context.ts.mark(\"userErrorMessage\", result, \"Error Message is Displayed\")\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\utilities\\teststatus.py\", line 68, in mark\n    assert True == False\n"}, "steps": [{"name": "Given User is on HomePage", "status": "passed", "start": 1620451248416, "stop": 1620451248416}, {"name": "When User clicks on the Sign In link", "status": "passed", "start": 1620451248416, "stop": 1620451249580}, {"name": "And User enters \"shankubisai5555@gmail.com\" as email", "status": "passed", "start": 1620451249580, "stop": 1620451249689}, {"name": "And User clicks Next Button", "status": "passed", "start": 1620451249689, "stop": 1620451249742}, {"name": "And User enters \"shanku12345#\" as password", "status": "passed", "start": 1620451249742, "stop": 1620451256902}, {"name": "And User clicks Sign In Button", "status": "passed", "start": 1620451256903, "stop": 1620451264965}, {"name": "Then error message \"This account cannot be found. Please use a different account or sign up for a new account..\" is displayed", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\steps\\loginpagesteps\\loginpagesteps.py\", line 68, in userErrorMessage\n    context.ts.mark(\"userErrorMessage\", result, \"Error Message is Displayed\")\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\utilities\\teststatus.py\", line 68, in mark\n    assert True == False\n"}, "attachments": [{"name": "screenshot", "source": "236b7cb0-55fc-4b39-9dd5-f6b016d9cc62-attachment.png", "type": "image/png"}], "start": 1620451264966, "stop": 1620451265277}], "parameters": [{"name": "email", "value": "shankubisai5555@gmail.com"}, {"name": "password", "value": "shanku12345#"}], "start": 1620451243347, "stop": 1620451265334, "uuid": "9a541568-e4a6-4e7c-bf8c-5022b474a2b0", "historyId": "acc7b0f29e3b6914511e55eaeaf402c7", "fullName": "LoginPage Validation: Verify Login with Invalid Credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "LoginPage Validation"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}