{"name": "Verify Login with Invalid Credentials -- @1.1 credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\bisai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\bisai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\steps\\loginpagesteps\\loginpagesteps.py\", line 68, in userErrorMessage\n    context.ts.mark(\"userErrorMessage\", result, \"Error Message is Displayed\")\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\utilities\\teststatus.py\", line 68, in mark\n    assert True == False\n"}, "steps": [{"name": "Given User is on HomePage", "status": "passed", "start": 1620464162659, "stop": 1620464162660}, {"name": "When User clicks on the Sign In link", "status": "passed", "start": 1620464162660, "stop": 1620464164578}, {"name": "And User enters \"shankubisai4444@gmail.com\" as email", "status": "passed", "start": 1620464164580, "stop": 1620464164933}, {"name": "And User clicks Next Button", "status": "passed", "start": 1620464164933, "stop": 1620464165067}, {"name": "And User enters \"shanku12345#\" as password", "status": "passed", "start": 1620464165068, "stop": 1620464172187}, {"name": "And User clicks Sign In Button", "status": "passed", "start": 1620464172187, "stop": 1620464180251}, {"name": "Then error message \"This account cannot be found. Please use a different account or sign up for a new account..\" is displayed", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\bisai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\bisai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\steps\\loginpagesteps\\loginpagesteps.py\", line 68, in userErrorMessage\n    context.ts.mark(\"userErrorMessage\", result, \"Error Message is Displayed\")\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\utilities\\teststatus.py\", line 68, in mark\n    assert True == False\n"}, "start": 1620464180253, "stop": 1620464228827}], "parameters": [{"name": "email", "value": "shankubisai4444@gmail.com"}, {"name": "password", "value": "shanku12345#"}], "start": 1620464157876, "stop": 1620464229087, "uuid": "42d1f861-290c-4c15-afc8-7c7db3a58840", "historyId": "520ace4a85fda4d2d41e9599fab078c0", "fullName": "LoginPage Validation: Verify Login with Invalid Credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "LoginPage Validation"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}