{"name": "Verify Login with Invalid Credentials -- @1.1 credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\steps\\loginpagesteps\\loginpagesteps.py\", line 68, in userErrorMessage\n    context.ts.mark(\"userErrorMessage\", result, \"Error Message is Displayed\")\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\utilities\\teststatus.py\", line 68, in mark\n    assert True == False\n"}, "steps": [{"name": "Given User is on HomePage", "status": "passed", "start": 1620451226432, "stop": 1620451226432}, {"name": "When User clicks on the Sign In link", "status": "passed", "start": 1620451226432, "stop": 1620451227593}, {"name": "And User enters \"shankubisai4444@gmail.com\" as email", "status": "passed", "start": 1620451227594, "stop": 1620451227698}, {"name": "And User clicks Next Button", "status": "passed", "start": 1620451227699, "stop": 1620451227749}, {"name": "And User enters \"shanku12345#\" as password", "status": "passed", "start": 1620451227750, "stop": 1620451234901}, {"name": "And User clicks Sign In Button", "status": "passed", "start": 1620451234901, "stop": 1620451242917}, {"name": "Then error message \"This account cannot be found. Please use a different account or sign up for a new account..\" is displayed", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bisai\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\steps\\loginpagesteps\\loginpagesteps.py\", line 68, in userErrorMessage\n    context.ts.mark(\"userErrorMessage\", result, \"Error Message is Displayed\")\n  File \"C:\\Users\\bisai\\OneDrive - Kudelski Group\\Desktop\\Desktop\\Study\\4Selenium with Python(letskodeit)\\WebTestFrameworkBDD\\utilities\\teststatus.py\", line 68, in mark\n    assert True == False\n"}, "attachments": [{"name": "screenshot", "source": "43a6ee36-78f3-4c41-a6e0-e47cac160958-attachment.png", "type": "image/png"}], "start": 1620451242917, "stop": 1620451243200}], "parameters": [{"name": "email", "value": "shankubisai4444@gmail.com"}, {"name": "password", "value": "shanku12345#"}], "start": 1620451221207, "stop": 1620451243343, "uuid": "f46baba9-80be-4414-8ca6-c87a95b3caed", "historyId": "520ace4a85fda4d2d41e9599fab078c0", "fullName": "LoginPage Validation: Verify Login with Invalid Credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "LoginPage Validation"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}